//Given two strings s and t which consist of only lowercase letters
//String t is generated by random shuffling string s and then add one more letter at a random position.
//Find the leeter that was added in t


// Example:
// Input:
// s = "abcd"
// t = "abcde"
//
// Output:
// e

import java.util.HashMap;


public class findTheDifference {
    public  char FindTheDifference(String s, String t) {
        HashMap <Character, Integer> map = new HashMap<>();
        for (char c: s.toCharArray()) {
            map.put(c, map.getOrDefault(c, 0) + 1);
        }

        for(char c: t.toCharArray()) {
            if (!map.containsKey(c) || map.get(c) == 0) {
                return c;
            } else {
                map.put(c, map.get(c) - 1);
            }
        }
        return '!';
    }
}
